/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampil;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;

/**
 *
 * @author ITAdmin
 */
public final class BarangMasuk extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    public String kdbrg, nmbrg, kategbrg, mrk, uk;
    public String kdlok, nmlok;
    private DefaultTableModel tabmode;
    /**
     * Creates new form InventarisMasuk
     */
    public BarangMasuk() {
        initComponents();
                      
        kosong();
        aktif();
        autonumber();
        
        datatable();
        
        txtnm.setEditable(false);
        txtkd.setEditable(false);
        txtmrk.setEditable(false);
        txtuk.setEditable(false);
        txtkdlok.setEditable(false);
        txtnmlok.setEditable(false);
    }
    
   

    protected void aktif() {
        txtkd.requestFocus();
        jtgl.setEditor(new JSpinner.DateEditor(jtgl, "yyyy/MM/dd"));
//        Object[] baris = {"KD Barang", "Nama", "Harga Beli", "Harga Jual", "Qty", "Total"};
//        tabmode = new DefaultTableModel(null, baris);
//        tableinvmsk.setModel(tabmode);
    }

    protected void kosong() {
        txtkd.setText("");
        txtnm.setText("");
        txtktg.setText("");
        txtmrk.setText("");
        txtuk.setText("");
        txtjml.setText("");
        txtnil.setText("");
        txtkdlok.setText("");
        txtnmlok.setText("");
    }

    protected void autonumber() {
        try {
            String sql = "SELECT kode_barang_masuk FROM barang_masuk ORDER BY kode_barang_masuk DESC LIMIT 1";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            txtidinv.setText("IN0001");
            while (hasil.next()) {
                System.out.println(hasil.getString("kode_barang_masuk").substring(2));
                String id = hasil.getString("kode_barang_masuk").substring(2);
                int AN = Integer.parseInt(id) + 1;
                String Nol = "";

                if (AN < 10) {
                    Nol = "000";
                } else if (AN < 100) {
                    Nol = "00";
                } else if (AN < 1000) {
                    Nol = "0";
                } else if (AN < 10000) {
                    Nol = "";
                }

                txtidinv.setText("IN" + Nol + AN);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Auto number gagal " + e);
        }
    }
    
    public void itemTerpilih() {
        Barang pp = new Barang();
        pp.brg = this;
        txtkd.setText(kdbrg);
        txtnm.setText(nmbrg);
        txtktg.setText(kategbrg);
        txtmrk.setText(mrk);
        txtuk.setText(uk);
    }
    
    public void lokasiTerpilih() {
        PLokasi pp = new PLokasi();
        pp.lks = this;
        txtkdlok.setText(kdlok);
        txtnmlok.setText(nmlok);
    }
    
    protected void datatable(){
        Object[] Baris = {"ID Barang Masuk", "Kode Barang", "jumlah", "Nilai","Tanggal Masuk","Kode Lokasi"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();            
        try{
            String sql ="SELECT * FROM barang_masuk WHERE kode_barang like '%"+cariitem+"%' or kode_barang_masuk like '%"+cariitem+"%' order by kode_barang_masuk asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6)                    
                });
            }
            tableinvmsk.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal di panggil"+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidinv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtgl = new javax.swing.JSpinner();
        bkeluar = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        bcaribrg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtktg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmrk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtuk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtkdlok = new javax.swing.JTextField();
        bcarilok = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtnmlok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtjml = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtnil = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableinvmsk = new javax.swing.JTable();
        backGround1 = new tampil.BackGround();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("Barang MASUK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 24, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ID Barang Masuk");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 127, -1, -1));
        jPanel1.add(txtidinv, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 125, 233, 31));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Tanggal Masuk");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 127, -1, -1));

        jtgl.setModel(new javax.swing.SpinnerDateModel());
        jPanel1.add(jtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 125, 202, 31));

        bkeluar.setBackground(new java.awt.Color(0, 255, 204));
        bkeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        bbatal.setBackground(new java.awt.Color(255, 255, 0));
        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        jPanel1.add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 316, 72, 35));

        bhapus.setBackground(new java.awt.Color(255, 0, 255));
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 316, 88, 35));

        bubah.setBackground(new java.awt.Color(102, 102, 255));
        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 316, 98, 34));

        bsimpan.setBackground(new java.awt.Color(0, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 316, 101, 34));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Kode Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 162, -1, -1));

        txtkd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtkd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdActionPerformed(evt);
            }
        });
        jPanel1.add(txtkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 162, 160, -1));

        bcaribrg.setBackground(new java.awt.Color(204, 204, 255));
        bcaribrg.setText("Cari");
        bcaribrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaribrgActionPerformed(evt);
            }
        });
        jPanel1.add(bcaribrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 163, 80, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nama Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 203, -1, -1));

        txtnm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 198, 246, 28));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Kategori Barang");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 235, -1, -1));

        txtktg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtktg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtktgActionPerformed(evt);
            }
        });
        jPanel1.add(txtktg, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 232, 249, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Merek");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 265, -1, -1));

        txtmrk.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(txtmrk, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 261, 249, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Ukuran");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 299, 59, -1));

        txtuk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 296, 249, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Kode Lokasi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 185, -1, -1));

        txtkdlok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtkdlok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdlokActionPerformed(evt);
            }
        });
        jPanel1.add(txtkdlok, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 182, 163, -1));

        bcarilok.setBackground(new java.awt.Color(204, 204, 255));
        bcarilok.setText("Cari");
        bcarilok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcarilokActionPerformed(evt);
            }
        });
        jPanel1.add(bcarilok, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 176, 68, 36));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Nama Lokasi");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 219, -1, -1));

        txtnmlok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtnmlok, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 216, 237, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 253, -1, -1));

        txtjml.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlActionPerformed(evt);
            }
        });
        jPanel1.add(txtjml, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 250, 237, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("harga");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 285, -1, -1));

        txtnil.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtnil, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 282, 237, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("List Data Barang Masuk :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 330, 163, -1));

        txtcari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 357, 394, -1));

        bcari.setBackground(new java.awt.Color(0, 255, 255));
        bcari.setText("cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel1.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 358, 101, -1));

        tableinvmsk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableinvmsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableinvmskMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableinvmsk);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 381, 825, 198));

        javax.swing.GroupLayout backGround1Layout = new javax.swing.GroupLayout(backGround1);
        backGround1.setLayout(backGround1Layout);
        backGround1Layout.setHorizontalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        backGround1Layout.setVerticalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(backGround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtkdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkdActionPerformed

    private void bcaribrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaribrgActionPerformed
        Barang pp = new Barang();
        pp.brg = this;
        pp.setVisible(true);
        pp.setResizable(false);
    }//GEN-LAST:event_bcaribrgActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data ini?", "konfirm dialog", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "DELETE FROM barang_masuk WHERE kode_barang_masuk='"+txtidinv.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
                kosong();
                txtkd.requestFocus();
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal di hapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        String sql = "UPDATE barang_masuk SET kode_barang=?,jumlah=?,harga=?,tgl=?,kode_lokasi=? WHERE kode_barang_masuk='"+txtidinv.getText()+"'";
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fd = sdf.format(jtgl.getValue());
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkd.getText());
            stat.setString(2, txtjml.getText());
            stat.setString(3, txtnil.getText());
            stat.setString(4, fd);
            stat.setString(5, txtkdlok.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            kosong();
            txtkd.requestFocus();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal di ubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "INSERT INTO barang_masuk VALUES (?,?,?,?,?,?)";
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String fd = sdf.format(jtgl.getValue());
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtidinv.getText());
            stat.setString(2, txtkd.getText());
            stat.setString(3, txtjml.getText());
            stat.setString(4, txtnil.getText());
            stat.setString(5, fd);            
            stat.setString(6, txtkdlok.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            kosong();
            txtkd.requestFocus();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal di simpan"+e);
        }
        datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void txtjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlActionPerformed

    private void txtkdlokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdlokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkdlokActionPerformed

    private void bcarilokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcarilokActionPerformed
        PLokasi pp = new PLokasi();
        pp.lks = this;
        pp.setVisible(true);
        pp.setResizable(false);
    }//GEN-LAST:event_bcarilokActionPerformed

    private void txtktgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtktgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtktgActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
     datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void tableinvmskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableinvmskMouseClicked
      int bar = tableinvmsk.getSelectedRow();
        String id_inv = tabmode.getValueAt(bar, 0).toString();
        String kd_brg = tabmode.getValueAt(bar, 1).toString();
        String jml = tabmode.getValueAt(bar, 2).toString();
        String nil = tabmode.getValueAt(bar, 3).toString();
//        String tgl = tabmode.getValueAt(bar, 4).toString();
        String kd_lok = tabmode.getValueAt(bar, 6).toString();
        try{
            String sql = "SELECT * FROM data_barang WHERE kode_barang='"+kd_brg+"'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) {
                txtnm.setText(hasil.getString("nama_barang"));
                txtktg.setText(hasil.getString("kategori"));
                txtmrk.setText(hasil.getString("merek_barang"));
                txtuk.setText(hasil.getString("ukuran"));
            }    
            String sql2 = "SELECT * FROM lokasi_barang WHERE kode_lokasi='"+kd_lok+"'";
            Statement stat2 = conn.createStatement();
            ResultSet hasil2 = stat2.executeQuery(sql2);
            if (hasil2.next()) {
                txtkdlok.setText(hasil2.getString("kode_lokasi"));
                txtnmlok.setText(hasil2.getString("nama_lokasi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil " + e);
        }
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
//        String fd = sdf.format(jtgl.setValue(tgl));
        txtkd.setText(kd_brg);
        txtjml.setText(jml);
        txtnil.setText(nil);
//        jtgl.setV(tgl);
        txtkdlok.setText(kd_lok);
    }//GEN-LAST:event_tableinvmskMouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tampil.BackGround backGround1;
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bcaribrg;
    private javax.swing.JButton bcarilok;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jtgl;
    private javax.swing.JTable tableinvmsk;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtidinv;
    private javax.swing.JTextField txtjml;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txtkdlok;
    private javax.swing.JTextField txtktg;
    private javax.swing.JTextField txtmrk;
    private javax.swing.JTextField txtnil;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnmlok;
    private javax.swing.JTextField txtuk;
    // End of variables declaration//GEN-END:variables
}
